### ISSUE TITLE
Failed to compile with lua5.2.1

### ISSUE THREAD

**Issue by isaiah** [Cofyc/lua-ssocket#1]
error log:

```
cc -Wall -O2 -g -std=c99 -pedantic -fPIC --shared -o socket.so socket.c timeout.c buffer.c
socket.c: In function ‘__getsockaddrfromarg’:
socket.c:176:57: error: ‘struct hostent’ has no member named ‘h_addr’
socket.c: In function ‘__makesockaddr’:
socket.c:221:22: error: ‘NI_MAXHOST’ undeclared (first use in this function)
socket.c:221:22: note: each undeclared identifier is reported only once for each function it appears in
socket.c:222:13: warning: implicit declaration of function ‘getnameinfo’ [-Wimplicit-function-declaration]
socket.c:223:35: error: ‘NI_NUMERICHOST’ undeclared (first use in this function)
socket.c:227:17: warning: implicit declaration of function ‘gai_strerror’ [-Wimplicit-function-declaration]
socket.c:227:17: warning: passing argument 2 of ‘lua_pushstring’ makes pointer from integer without a cast [enabled by default]
In file included from socket.c:1:0:
/usr/include/lua.h:205:22: note: expected ‘const char *’ but argument is of type ‘int’
socket.c:221:18: warning: unused variable ‘buf’ [-Wunused-variable]
socket.c:241:9: warning: passing argument 2 of ‘lua_pushstring’ makes pointer from integer without a cast [enabled by default]
In file included from socket.c:1:0:
/usr/include/lua.h:205:22: note: expected ‘const char *’ but argument is of type ‘int’
socket.c: In function ‘socket_getaddrinfo’:
socket.c:469:21: error: storage size of ‘hints’ isn’t known
socket.c:476:5: warning: implicit declaration of function ‘getaddrinfo’ [-Wimplicit-function-declaration]
socket.c:479:9: warning: passing argument 2 of ‘lua_pushstring’ makes pointer from integer without a cast [enabled by default]
In file included from socket.c:1:0:
/usr/include/lua.h:205:22: note: expected ‘const char *’ but argument is of type ‘int’
socket.c:484:60: error: dereferencing pointer to incomplete type
socket.c:485:19: error: ‘NI_MAXHOST’ undeclared (first use in this function)
socket.c:485:37: error: ‘NI_MAXSERV’ undeclared (first use in this function)
socket.c:486:29: error: dereferencing pointer to incomplete type
socket.c:486:48: error: dereferencing pointer to incomplete type
socket.c:492:35: error: dereferencing pointer to incomplete type
socket.c:495:35: error: dereferencing pointer to incomplete type
socket.c:498:35: error: dereferencing pointer to incomplete type
socket.c:501:35: error: dereferencing pointer to incomplete type
socket.c:501:60: error: dereferencing pointer to incomplete type
socket.c:485:32: warning: unused variable ‘sbuf’ [-Wunused-variable]
socket.c:485:14: warning: unused variable ‘hbuf’ [-Wunused-variable]
socket.c:510:5: warning: implicit declaration of function ‘freeaddrinfo’ [-Wimplicit-function-declaration]
socket.c:469:21: warning: unused variable ‘hints’ [-Wunused-variable]
socket.c: In function ‘luaopen_socket_c’:
socket.c:1270:5: error: ‘AI_NUMERICHOST’ undeclared (first use in this function)
socket.c:1271:5: error: ‘AI_NUMERICSERV’ undeclared (first use in this function)
make: *** [socket.so] Error 1
```
